### ISSUE TITLE
How to run the jobs on multiple GPUs.

### ISSUE THREAD

**Issue by PkuRainBow** [Britefury/cutmix-semisup-seg#1]
Great job for the semi-supervised semantic segmentation problem!

After checking the implementations, we do not find the related code to support running jobs with multiple GPUs,

We only find that the job function in the job_helper.py contains a parameter "num_jobs" as shown below,

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/job_helper.py#L87-L116

**Comment by Britefury** [comment]
Ahhh yes, that code was there from when it was being run on a very specific cluster setup and was generic code.
Unfortunately there is no way to run this on multiple GPUs I'm afraid.
Personally, if I have more than 1 GPU available, I tend to run multiple experiments in parallel.
