### ISSUE TITLE
Confused on the "loss_mask"

### ISSUE THREAD

**Issue by PkuRainBow** [Britefury/cutmix-semisup-seg#6]
Hi, really nice codebase!

We have tried to understand the details of your implementation and find the usage of the loss mask a little bit confusing (as shown below).

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/train_seg_semisup_mask_mt.py#L294-L297

First, I have checked the code carefully and find that you define the 'mask' for the unlabeled images at the following code snippet:

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/datapipe/seg_data.py#L90-L96

Therefore, we can see that the initial 'mask' for all images is set as an array of 255 with the same size as the input image. Then you assign the mask value as following:

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/datapipe/seg_transforms_cv.py#L198

According to my understanding, only when we apply the cv2.warpAffine transform, some of the 'mask' values become zero (as shown below):

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/datapipe/seg_transforms_cv.py#L371-L372

If my understanding is correct, the  **batch_um0** and **batch_um1** might not be necessary if we do not apply the warpAffine transformation.  

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/train_seg_semisup_mask_mt.py#L294-L297

**So my first question is about the influence of **affine.cat_nx2x3** (shown as below) on the final performance.** 

https://github.com/Britefury/cutmix-semisup-seg/blob/3a8839c7145052ef1e5d0e5862500c6c95b4a042/datapipe/seg_transforms_cv.py#L350-L356

So I guess the purpose of the loss mask is mainly to **filter out the influence of the extra introduced pixels when applying the warpAffine augmentation.**  Is my understanding correct?

**It would be great if you could point out any of my misunderstandings!**

**Comment by Britefury** [comment]
You've pretty much got it. When a rotation/`cv2.warpAffine` is applied, there is a chance that the input image crop will have some pixels drawn from outside the bounds of the input image, likely resulting in either black or zero-values pixels (I can't recall which precisely).
There is no point having consistency loss apply to the predictions resulting form these out of bounds pixels, so the loss mask turns it off here. You are correct that the loss mask is redundant when `cv2.warpAffine` isn't used.
I'm not sure what you mean by the influence of `affine.cat_nx2x3` on the final performance. It is a transformation matrix concatenation function.

**Comment by PkuRainBow** [comment]
@Britefury Thanks for your quick reply.

In fact, my second question can be rephrased as "have you ever trained the models w/o using the rotation augmentation (therefore, also w/o using the loss mask)?"

According to my experience, most of the state-of-the-art semantic segmentation methods such as DeepLabv3/v3+ has not adopted the rotation augmentation.

In fact, in our implementation, we also do not apply the rotation augmentation, so in fact, we also do not need to use the loss mask, right?

Great thanks again!

**Comment by Britefury** [comment]
None of the Pascal VOC 2012 and Cityscapes models were trained with rotation; only the ISIC 2012 models.

Come to think of it, there is one other situation where the loss mask is used; a randomly chosen scale factor can result in e.g. a 500x500 crop being drawn from the source image and scaled down to the 321x321 training crop size. If the image has a width/height of less than 500px, then blank pixels will appear on either side, and the loss mask will be 0.

You do not need the loss mask if you can guarantee no blank pixels will come through.

To be honest, I haven't verified if the loss mask is indeed necessary or effective. I just thought that learning - even using unsupervised loss - on blank pixels was pointless and could hypothetically waste some network capacity. I haven't verified it's effect one way or the other. You may well get good results without it.

**Comment by PkuRainBow** [comment]
Great thanks again!

**Comment by Britefury** [comment]
Given that you are not the only person to be confused by this, I have added some comments!
